version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3 # primary container
    steps:
      - checkout # checkout the code primary directory
      - run echo "Hello World!" # run the echo command